[phases.setup]
nixpkgs = ["php83", "nodejs_20", "npm-9_x", "composer"]

[phases.install]
cmds = ["composer install --no-interaction --prefer-dist", "npm install"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "vendor/bin/heroku-php-apache2 public/"

[env]
PORT = "8080"
